language: python

python:
  - "3.7"

before_install:
  - which "python"
  - python -c "import sys; print(sys.path);"

addons:
  apt:
    packages:
      - inkscape
      - gnuplot
      - ghostscript
cache:
  directories:
    - $HOME/.local/texlive

install:
  - python bin/downloads.py
  - pip install -r requirements.txt
  # We need SCons > 3.1.1 (SCons <=3.1.1 has a bug, as described in issue #72)
  - (mkdir -p ./tmp/scons && cd ./tmp/scons && curl -sL https://github.com/SCons/scons/archive/master.tar.gz | tar -xz --strip-components=1 -f -)
  - if [ -e "$HOME/.local/texlive/bin/x86_64-linux" ]; then
      echo "$HOME/.local/texlive/bin/x86_64-linux EXISTS";
    else
      echo "$HOME/.local/texlive/bin/x86_64-linux DOES NOT EXIST";
      python bin/install-tex.py --repository="http://ctan.math.washington.edu/tex-archive/systems/texlive/tlnet";
    fi
  - PATH="$HOME/.local/texlive/bin/x86_64-linux:$PATH"

before_script:
  - echo $PATH
  # We need SCons > 3.1.1 (SCons <=3.1.1 has a bug, as described in issue #72)
  # - scons --version
  - ./tmp/scons/src/script/scons.py --version

script:
  #- scons
  - ./tmp/scons/src/script/scons.py
